noun =input("Can you give me a noun?")
adjective =input("Can you give an adjective?")
adverb =input("Can you give me an adverb?")
verb =input("Can you give me a verb?")
print("On a tropical " + noun)
print("Underneath a " + adjective + " moon")
print("Hanging' " + adverb +)
print(verb+ "questions cause they got all the answers ")
